name: Update development base image

on:
  push:
    branches: [ master ]
    paths:
    - sample_configs/*
    - composer.*
    - .github/*
    - .devcontainer/*
  workflow_dispatch:
    inputs:
      ref:
        description: Branch, tag, or commit SHA to build against
        required: false
        default: master
      docker-tag:
        description: Tag to add to the Docker image
        required: false
        default: latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref || 'master' }}
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/universityradioyork/myradio/dev-base:${{ github.event.inputs.docker-tag || 'latest' }}
    - name: Push
      run: docker push ghcr.io/universityradioyork/myradio/dev-base:${{ github.event.inputs.docker-tag || 'latest' }}
