name: Docker Image and Stack

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    uses: UniversityRadioYork/stacks/.github/workflows/build.yml@main
    with:
      stack: myradio
      environment: staging
      image: MyRadio
      tag: ${{ github.sha }}
